### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by not4Pedro** [taranis-ai/taranis.ai#35]
- Assess: replace Flilters and Items lists with an annotated screenshot of all the properties a NewsItem (or Story) and Filter
- Publish: screenshot and short description of a product (similar to Analyze)
- User settings - adding new fields and adding a screenshot
- ~~revisit user stories so it feels more natural~~
- (if possible) Move the section Workflow [Analyst] [here](https://taranis.ai/docs/user-stories/analyst-stories/) to the top of the page.

**Comment by stefaniasava** [comment]
I’ve completed the first three tasks. The last point about revisiting user stories is unclear and will need more information to proceed.

**Comment by not4Pedro** [comment]
@stefaniasava it looks solid.
#### Please:
- Change the Story picture for a not visually broken picture (a picture with a greater width should do it)
- Take a story that includes tags (you can even add tags, but it would be better to include something with tags coming from a Bot, check dev or stage instance)
- Annotate the whole Story card: Published, Tags (you can move/use the info from the Fitler picture), Vote (who can vote, how many votes one has (one per user, per story)), Article link, relevance score, source picture, Title, Summary (mention, what is the default text and that it can be changed by adding Summary or review (check what is true and mention the logic a bit))
- On the right-hand side, annotate each and every button, and point the arrows precisely to the buttons because they are so close to each other (specifically the first arrow at the top is not clear where it's pointing), I am not sure if the colour of the arrow on that picture is the best, check for readability

#### Nitpick
- I am personally confused about the word: **modal**. Is that really what it is?
- Consider aligning the text bubbles somehow, so it would have like some kind of same spacing to the other bubbles
